version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    image: php:7-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - nginx